name = "opengrid"
compatibility_date = "2026-04-06"
compatibility_flags = ["nodejs_compat"]
main = "dist/_worker.js"

[assets]
directory = "dist"
binding = "ASSETS"
[[d1_databases]]
binding = "DB"
database_name = "opengrid"
database_id = "003ca203-3212-452c-ac19-1c778ec2c5ad"
